### PR TITLE
Lua 5.1 compatibility

### PR DESCRIPTION
**Pull request by smarek**
- Lua runtime updated syntax for used bitop, lua-struct and lua-utf8 modules
  - inspired from https://github.com/Johnnynator/kaitai_struct_luajit_runtime
- Compiler Lua translator rewritten all bitwise operations to use `bit` library
- Tests runner updated to run tests with Lua 5.1, with single call change, `xpcall` in Lua5.1 takes 2 args instead of varargs

This is also related to PR https://github.com/kaitai-io/ci_targets/pull/7

### CODE REVIEW

**Comment by ildar** [comment]
Thanks for an invitation.
1. This PR effectively replaces Lua 5.3 with Lua 5.1. Is this what's intended? Or you wanted dual-Lua compatibility?
2. There's [compat-53](https://luarocks.org/modules/siffiejoe/compat53) library aimed to unify 5.3 features in 5.1 environment. Good for dual-targeting and migration.

**Comment by smarek** [comment]
@ildar thank you for review

  1. yes, i think so
      - given this: https://github.com/kaitai-io/kaitai_struct_lua_runtime/issues/1#issuecomment-671080974
      - there should be only one Lua target currently, that is 5.1+ compatible
  2. compat library nice, thank you, but it does not have the necessary bitwise operations, so maybe in future

**Comment by ildar** [comment]
on (2): plz take a look:
https://github.com/keplerproject/lua-compat-5.3/commit/7e2b0b5e5f55cac22fbd9237bf1c354df134802c

**Comment by smarek** [comment]
oh, so similar to bitop, i'll consider re-working the PR eventually, thank you

would it somehow be even possible to backport the bitwise operators (eg. `1 << 2`)
i smell it could be possible in C API maybe, but i'm totally clueless

**Comment by ildar** [comment]
https://github.com/keplerproject/lua-compat-5.3/blob/master/lbitlib.c#L99

**Comment by ildar** [comment]
on (1) I just read the whole discussion. I perceive @GreyCat sympathised
Dual-lua-targeting, calling it cross-platform-ing later:
https://github.com/kaitai-io/kaitai_struct_lua_runtime/issues/1#issuecomment-403495055
I suggest suporting dual/triple-Lua-versions as:

   1. it looks like there are users for 5.3, 5.1 and even 5.2 (rare in the
   Lua community yet demanded because of WShark);
   2. it corresponds to current Lua community trends as many Lua libraries
   are 5.1 and 5.3 compatible (check LuaRocks.org)

One added issue to solve is testing: Kaitai would better be tested with all
2 (or 3) Lua versions. But this IMHO could be postponed for a later fix.

**Comment by smarek** [comment]
Final solution should be compatible 5.1+ and agree, so i'll update ci_targets with matrix of testing for each specific lua version

**Pull request closed without merging**
