### PR TITLE
Update go version

### PR DESCRIPTION
**Pull request by cugu**
This should fix the completely failing go tests

### CODE REVIEW

**Comment by GreyCat** [comment]
Let's try it, although I suspect it would require `sudo`...
Would you want direct push access to this repo, so you can experiment with integrations without doing pull requests on every occasion?

**Comment by cugu** [comment]
Sure, that could be useful. Thanks!

**Comment by GreyCat** [comment]
Well, yup, it failed: https://travis-ci.org/kaitai-io/kaitai_struct/jobs/360866890#L2703

**Comment by cugu** [comment]
Yes, travis gimmi is not up to date as well.

**Comment by GreyCat** [comment]
I've sent in the invitation, after accepting it, you should be able to contribute to most team repos directly. Please continue to use PRs for most non-trivial changes, though, as it allows us to peer review the commits.

**Pull request merged**
